<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProvinciasSeeder extends Seeder
{
    public function run(): void
    {
        $departamentos = DB::table('departamentos')->pluck('id_departamento', 'nombre_departamento');

        $provincias = [
            // CHUQUISACA
            ['nombre_provincia' => 'Belisario Boeto', 'id_departamento' => $departamentos['Chuquisaca']],
            ['nombre_provincia' => 'Hernando Siles', 'id_departamento' => $departamentos['Chuquisaca']],
            ['nombre_provincia' => 'Jaime Zudáñez', 'id_departamento' => $departamentos['Chuquisaca']],
            ['nombre_provincia' => 'Juana Azurduy de Padilla', 'id_departamento' => $departamentos['Chuquisaca']],
            ['nombre_provincia' => 'Luis Calvo', 'id_departamento' => $departamentos['Chuquisaca']],
            ['nombre_provincia' => 'Nor Cinti', 'id_departamento' => $departamentos['Chuquisaca']],
            ['nombre_provincia' => 'Oropeza', 'id_departamento' => $departamentos['Chuquisaca']],
            ['nombre_provincia' => 'Sud Cinti', 'id_departamento' => $departamentos['Chuquisaca']],
            ['nombre_provincia' => 'Tomina', 'id_departamento' => $departamentos['Chuquisaca']],
            ['nombre_provincia' => 'Yamparáez', 'id_departamento' => $departamentos['Chuquisaca']],
            ['nombre_provincia' => 'Otro', 'id_departamento' => $departamentos['Chuquisaca']],
            // COCHABAMBA
            ['nombre_provincia' => 'Arani', 'id_departamento' => $departamentos['Cochabamba']],
            ['nombre_provincia' => 'Arque', 'id_departamento' => $departamentos['Cochabamba']],
            ['nombre_provincia' => 'Ayopaya', 'id_departamento' => $departamentos['Cochabamba']],
            ['nombre_provincia' => 'Bolívar', 'id_departamento' => $departamentos['Cochabamba']],
            ['nombre_provincia' => 'Capinota', 'id_departamento' => $departamentos['Cochabamba']],
            ['nombre_provincia' => 'Carrasco', 'id_departamento' => $departamentos['Cochabamba']],
            ['nombre_provincia' => 'Cercado', 'id_departamento' => $departamentos['Cochabamba']],
            ['nombre_provincia' => 'Chapare', 'id_departamento' => $departamentos['Cochabamba']],
            ['nombre_provincia' => 'Esteban Arce', 'id_departamento' => $departamentos['Cochabamba']],
            ['nombre_provincia' => 'Germán Jordán', 'id_departamento' => $departamentos['Cochabamba']],
            ['nombre_provincia' => 'Mizque', 'id_departamento' => $departamentos['Cochabamba']],
            ['nombre_provincia' => 'Narciso Campero', 'id_departamento' => $departamentos['Cochabamba']],
            ['nombre_provincia' => 'Punata', 'id_departamento' => $departamentos['Cochabamba']],
            ['nombre_provincia' => 'Quillacollo', 'id_departamento' => $departamentos['Cochabamba']],
            ['nombre_provincia' => 'Tapacarí', 'id_departamento' => $departamentos['Cochabamba']],
            ['nombre_provincia' => 'Tiraque', 'id_departamento' => $departamentos['Cochabamba']],
            ['nombre_provincia' => 'Otro', 'id_departamento' => $departamentos['Cochabamba']],
            // BENI
            ['nombre_provincia' => 'Cercado', 'id_departamento' => $departamentos['Beni']],
            ['nombre_provincia' => 'Iténez', 'id_departamento' => $departamentos['Beni']],
            ['nombre_provincia' => 'José Ballivián', 'id_departamento' => $departamentos['Beni']],
            ['nombre_provincia' => 'Mamoré', 'id_departamento' => $departamentos['Beni']],
            ['nombre_provincia' => 'Marbán', 'id_departamento' => $departamentos['Beni']],
            ['nombre_provincia' => 'Moxos', 'id_departamento' => $departamentos['Beni']],
            ['nombre_provincia' => 'Vaca Díez', 'id_departamento' => $departamentos['Beni']],
            ['nombre_provincia' => 'Yacuma', 'id_departamento' => $departamentos['Beni']],
            ['nombre_provincia' => 'Otro', 'id_departamento' => $departamentos['Beni']],
            // LA PAZ
            ['nombre_provincia' => 'Abel Iturralde', 'id_departamento' => $departamentos['La Paz']],
            ['nombre_provincia' => 'Aroma', 'id_departamento' => $departamentos['La Paz']],
            ['nombre_provincia' => 'Bautista Saavedra', 'id_departamento' => $departamentos['La Paz']],
            ['nombre_provincia' => 'Caranavi', 'id_departamento' => $departamentos['La Paz']],
            ['nombre_provincia' => 'Eliodoro Camacho', 'id_departamento' => $departamentos['La Paz']],
            ['nombre_provincia' => 'Franz Tamayo', 'id_departamento' => $departamentos['La Paz']],
            ['nombre_provincia' => 'Gualberto Villarroel', 'id_departamento' => $departamentos['La Paz']],
            ['nombre_provincia' => 'Ingavi', 'id_departamento' => $departamentos['La Paz']],
            ['nombre_provincia' => 'Inquisivi', 'id_departamento' => $departamentos['La Paz']],
            ['nombre_provincia' => 'José Manuel Pando', 'id_departamento' => $departamentos['La Paz']],
            ['nombre_provincia' => 'José Ramón Loayza', 'id_departamento' => $departamentos['La Paz']],
            ['nombre_provincia' => 'Larecaja', 'id_departamento' => $departamentos['La Paz']],
            ['nombre_provincia' => 'Los Andes', 'id_departamento' => $departamentos['La Paz']],
            ['nombre_provincia' => 'Manco Kapac', 'id_departamento' => $departamentos['La Paz']],
            ['nombre_provincia' => 'Muñecas', 'id_departamento' => $departamentos['La Paz']],
            ['nombre_provincia' => 'Nor Yungas', 'id_departamento' => $departamentos['La Paz']],
            ['nombre_provincia' => 'Omasuyos', 'id_departamento' => $departamentos['La Paz']],
            ['nombre_provincia' => 'Pacajes', 'id_departamento' => $departamentos['La Paz']],
            ['nombre_provincia' => 'Pedro Domingo Murillo', 'id_departamento' => $departamentos['La Paz']],
            ['nombre_provincia' => 'Sud Yungas', 'id_departamento' => $departamentos['La Paz']],
            ['nombre_provincia' => 'Otro', 'id_departamento' => $departamentos['La Paz']],
            // ORURO
            ['nombre_provincia' => 'Atahuallpa', 'id_departamento' => $departamentos['Oruro']],
            ['nombre_provincia' => 'Carangas', 'id_departamento' => $departamentos['Oruro']],
            ['nombre_provincia' => 'Cercado', 'id_departamento' => $departamentos['Oruro']],
            ['nombre_provincia' => 'Eduardo Avaroa', 'id_departamento' => $departamentos['Oruro']],
            ['nombre_provincia' => 'Ladislao Cabrera', 'id_departamento' => $departamentos['Oruro']],
            ['nombre_provincia' => 'Sabaya', 'id_departamento' => $departamentos['Oruro']],
            ['nombre_provincia' => 'Nor Carangas', 'id_departamento' => $departamentos['Oruro']],
            ['nombre_provincia' => 'Pantaleón Dalence', 'id_departamento' => $departamentos['Oruro']],
            ['nombre_provincia' => 'Poopó', 'id_departamento' => $departamentos['Oruro']],
            ['nombre_provincia' => 'Puerto de Mejillones', 'id_departamento' => $departamentos['Oruro']],
            ['nombre_provincia' => 'Sajama', 'id_departamento' => $departamentos['Oruro']],
            ['nombre_provincia' => 'San Pedro de Totora', 'id_departamento' => $departamentos['Oruro']],
            ['nombre_provincia' => 'Saucarí', 'id_departamento' => $departamentos['Oruro']],
            ['nombre_provincia' => 'Sebastián Pagador', 'id_departamento' => $departamentos['Oruro']],
            ['nombre_provincia' => 'Sud Carangas', 'id_departamento' => $departamentos['Oruro']],
            ['nombre_provincia' => 'Tomas Barrón', 'id_departamento' => $departamentos['Oruro']],
            ['nombre_provincia' => 'Otro', 'id_departamento' => $departamentos['Oruro']],
            // PANDO
            ['nombre_provincia' => 'Abuná', 'id_departamento' => $departamentos['Pando']],
            ['nombre_provincia' => 'Federico Román', 'id_departamento' => $departamentos['Pando']],
            ['nombre_provincia' => 'Madre de Dios', 'id_departamento' => $departamentos['Pando']],
            ['nombre_provincia' => 'Manuripi', 'id_departamento' => $departamentos['Pando']],
            ['nombre_provincia' => 'Nicolás Suárez', 'id_departamento' => $departamentos['Pando']],
            ['nombre_provincia' => 'Otro', 'id_departamento' => $departamentos['Pando']],
            // POTOSÍ
            ['nombre_provincia' => 'Alonso de Ibáñez', 'id_departamento' => $departamentos['Potosí']],
            ['nombre_provincia' => 'Antonio Quijarro', 'id_departamento' => $departamentos['Potosí']],
            ['nombre_provincia' => 'Bernardino Bilbao', 'id_departamento' => $departamentos['Potosí']],
            ['nombre_provincia' => 'Charcas', 'id_departamento' => $departamentos['Potosí']],
            ['nombre_provincia' => 'Chayanta', 'id_departamento' => $departamentos['Potosí']],
            ['nombre_provincia' => 'Cornelio Saavedra', 'id_departamento' => $departamentos['Potosí']],
            ['nombre_provincia' => 'Daniel Campos', 'id_departamento' => $departamentos['Potosí']],
            ['nombre_provincia' => 'Enrique Baldivieso', 'id_departamento' => $departamentos['Potosí']],
            ['nombre_provincia' => 'José María Linares', 'id_departamento' => $departamentos['Potosí']],
            ['nombre_provincia' => 'Modesto Omiste', 'id_departamento' => $departamentos['Potosí']],
            ['nombre_provincia' => 'Nor Chichas', 'id_departamento' => $departamentos['Potosí']],
            ['nombre_provincia' => 'Nor Lípez', 'id_departamento' => $departamentos['Potosí']],
            ['nombre_provincia' => 'Rafael Bustillo', 'id_departamento' => $departamentos['Potosí']],
            ['nombre_provincia' => 'Sud Chichas', 'id_departamento' => $departamentos['Potosí']],
            ['nombre_provincia' => 'Sud Lípez', 'id_departamento' => $departamentos['Potosí']],
            ['nombre_provincia' => 'Tomás Frías', 'id_departamento' => $departamentos['Potosí']],
            ['nombre_provincia' => 'Otro', 'id_departamento' => $departamentos['Potosí']],
            // SANTA CRUZ
            ['nombre_provincia' => 'Andres Ibañez', 'id_departamento' => $departamentos['Santa Cruz']],
            ['nombre_provincia' => 'Ángel Sandoval', 'id_departamento' => $departamentos['Santa Cruz']],
            ['nombre_provincia' => 'Chiquitos', 'id_departamento' => $departamentos['Santa Cruz']],
            ['nombre_provincia' => 'Cordillera', 'id_departamento' => $departamentos['Santa Cruz']],
            ['nombre_provincia' => 'Florida', 'id_departamento' => $departamentos['Santa Cruz']],
            ['nombre_provincia' => 'Germán Busch', 'id_departamento' => $departamentos['Santa Cruz']],
            ['nombre_provincia' => 'Guarayos', 'id_departamento' => $departamentos['Santa Cruz']],
            ['nombre_provincia' => 'Ichilo', 'id_departamento' => $departamentos['Santa Cruz']],
            ['nombre_provincia' => 'Ignacio Warnes', 'id_departamento' => $departamentos['Santa Cruz']],
            ['nombre_provincia' => 'José Miguel de Velasco', 'id_departamento' => $departamentos['Santa Cruz']],
            ['nombre_provincia' => 'Manuel María Caballero', 'id_departamento' => $departamentos['Santa Cruz']],
            ['nombre_provincia' => 'Ñuflo de Chávez', 'id_departamento' => $departamentos['Santa Cruz']],
            ['nombre_provincia' => 'Obispo Santistevan', 'id_departamento' => $departamentos['Santa Cruz']],
            ['nombre_provincia' => 'Sara', 'id_departamento' => $departamentos['Santa Cruz']],
            ['nombre_provincia' => 'Vallegrande', 'id_departamento' => $departamentos['Santa Cruz']],
            ['nombre_provincia' => 'Otro', 'id_departamento' => $departamentos['Santa Cruz']],
            // TARIJA
            ['nombre_provincia' => 'Aniceto Arce', 'id_departamento' => $departamentos['Tarija']],
            ['nombre_provincia' => 'Burdet O’Connor', 'id_departamento' => $departamentos['Tarija']],
            ['nombre_provincia' => 'Cercado', 'id_departamento' => $departamentos['Tarija']],
            ['nombre_provincia' => 'Eustaquio Méndez', 'id_departamento' => $departamentos['Tarija']],
            ['nombre_provincia' => 'Gran Chaco', 'id_departamento' => $departamentos['Tarija']],
            ['nombre_provincia' => 'José María Avilés', 'id_departamento' => $departamentos['Tarija']],
            ['nombre_provincia' => 'Otro', 'id_departamento' => $departamentos['Tarija']],

        ];

        DB::table('provincias')->insert($provincias);
    }
}
